### PR TITLE
Fix #29: new input `cabal-update: false` to skip 'cabal update'

### LINKED ISSUE #29: Remove cabal update from setup upon request
I feel like `cabal update` should not be part of the setup.  This is because `cabal update` will do *project specific work* and sometimes fail because of problems specific to the project.

For example:

image

Aside from this, the project may want to do `cabal update` after configuring the project, which duplicates work.

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #29: ~~don't run 'cabal update'.~~ New input `cabal-update` (default `true`) that can be set to `false` to turn off running `cabal update`.

~~This breaking behavior requires a major version bump (e.g. to v3.0.0).~~

### CODE REVIEW

**Comment by andreasabel** [comment]
I am not so sure about this change anymore.  I think of this setup action as a "batteries included", maybe for the price of some redundancy.

**Comment by jneira** [comment]
what about a config switch to disable it?

**Comment by andreasabel** [comment]
> what about a config switch to disable it?

Yes, that's an option, see https://github.com/haskell/actions/issues/29#issuecomment-1369668572.

**Comment by andreasabel** [comment]
CI: the "test project" seems to build even without `cabal update`: https://github.com/haskell/actions/actions/runs/3832554762/jobs/6522998203#step:5:5
```
Run cabal build
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
```

File: setup/src/opts.ts [hunk 1]
```diff
@@ -93,6 +93,7 @@ export function getOpts(
   const stackSetupGhc = (inputs['stack-setup-ghc'] || '') !== '';
   const stackEnable = (inputs['enable-stack'] || '') !== '';
   const matcherDisable = (inputs['disable-matcher'] || '') !== '';
+  const cabalUpdate = inputs['cabal-update'] !== 'false';
```
Comment (andreasabel) [inline setup/src/opts.ts:96]: Not sure if this is the customary check for setting a default `true` input to `false`.

File: .github/workflows/workflow.yml [hunk 2]
```diff
@@ -72,6 +72,7 @@ jobs:
         with:
           ghc-version: ${{ matrix.ghc }}
           cabal-version: ${{ matrix.cabal }}
+          cabal-update: false
```
Comment (jneira) [inline .github/workflows/workflow.yml:75]: hmm, should not we test the default value (true)? or it is being tested somehow?

File: setup/src/opts.ts (hunk 1 above)
Comment (jneira) [reply setup/src/opts.ts:96]: hmm i would follow the handling of other boolean params, for consistency shake

Comment (jneira) [reply setup/src/opts.ts:96]: from https://github.com/haskell/actions/blob/main/setup/README.md

> Note: "boolean" types are set/unset, not true/false. That is, setting any "boolean" to a value other than the empty string ("") will be considered true/set.

dont like it at all, cause seeting it to `false` make the option `true` but 🤷

Comment (jneira) [reply setup/src/opts.ts:96]: So maybe it needs a `disable-cabal-update`? like `disable-matcher`? omg 🤦

**Comment by jneira** [comment]
Thanks for making update optional, it would need change https://github.com/haskell/actions/blob/main/setup/README.md adding the new option

File: setup/src/opts.ts (hunk 1 above)
Comment (andreasabel) [reply setup/src/opts.ts:96]: @jneira: Thanks for digging into this!  
I also dislike the current policy.  Like you said, `disable-matcher: false` currently seems to _disable_ the matcher, and `enable-stack: false` would _enable_ stack.  This will definitely confuse readers of workflows, and opens the door to obfuscation.

Is `true`/`false` the only accepted way to set booleans in YAML/JSON?  What about `True`/`False`, `on`/`off`, `yes`/`no`?  Maybe the authors of this action wanted to avoid such minefields...

I wonder whether there isn't some core functionality for actions to parse boolean inputs in a robust way, so that we do not have to reinvent the wheel here.

File: .github/workflows/workflow.yml (hunk 2 above)
Comment (andreasabel) [reply .github/workflows/workflow.yml:75]: To test it, we need another toy project here that uses some packages from Hackage.  
(To my surprise, the current test project builds fine without ever having invoked `cabal update`.  I just uses GHC packages.)

**Comment by andreasabel** [comment]
> Thanks for making update optional, it would need change [`main`/setup/README.md](https://github.com/haskell/actions/blob/main/setup/README.md?rgh-link-date=2023-01-04T21%3A30%3A42Z) adding the new option

Ah, thanks for the alert!

File: setup/src/opts.ts (hunk 1 above)
Comment (andreasabel) [reply setup/src/opts.ts:96]: There seems to be [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) which accepts `true` and `false` and throws `SyntaxError`.

Comment (jneira) [reply setup/src/opts.ts:96]: yeah, another alternative could be extends the Default data type to track explicitly option default values and set to true cabal-uodate

 I would left changing options semantic to another pr, cause it will break compatibility

Comment (andreasabel) [reply setup/src/opts.ts:96]: Oh, there is a [`core.getBooleanInput(...)`](https://github.com/actions/toolkit/blob/b2d865f18051b214475dae41766e9970fd68ca12/packages/core/src/core.ts#L163-L183) [added in 2021](https://github.com/actions/toolkit/pull/725).

File: .github/workflows/workflow.yml (hunk 2 above)
Comment (andreasabel) [reply .github/workflows/workflow.yml]: I now added a test that uses something from Hackage, and it uncovered
- #158

File: setup/src/opts.ts (hunk 1 above)
Comment (andreasabel) [reply setup/src/opts.ts]: I settled for using a modified version of `getBooleanInput`: `parseYAMLBoolean`.

**Comment by andreasabel** [comment]
I now added the description of `cabal-update` to the README.

This PR is ready again.

File: setup/src/opts.ts [hunk 3]
```diff
@@ -93,6 +114,14 @@ export function getOpts(
   const stackSetupGhc = (inputs['stack-setup-ghc'] || '') !== '';
   const stackEnable = (inputs['enable-stack'] || '') !== '';
   const matcherDisable = (inputs['disable-matcher'] || '') !== '';
+  // Andreas, 2023-01-05, issue #29:
+  // 'cabal-update' has a default value, so we should get a proper boolean always.
+  // Andreas, 2023-01-06: This is not true if we use the action as a library.
+  // Thus, need to patch with default value here.
+  const cabalUpdate = parseYAMLBoolean(
```
Comment (jneira) [inline setup/src/opts.ts:121]: Hi, your solution is more correct than the actual behaviour.
However, i think the codebase should be consistently "incorrect" in this case.  It would be even more confusing to users having two ways to set options and being both opposites (setting "false")

So i think it would be better to keep actual semantics for a non breaking pr (using `skip-cabal-update` or `disable-cabal-update` and actual broken boolean behaviour) and in another breaking pr fix boolean semantics for all options at once. See https://github.com/actions/runner/issues/1483

But i also see the advantages of being partially correct so as you consider.

Comment (andreasabel) [reply setup/src/opts.ts:121]: Thanks for the re-review, @jneira !

Indeed, sticking to the current handling of "boolean" flags we would need a negative one like `skip-cabal-update`.  Personally, I prefer positive flags (maybe because as a constructivist I shun double negation).  So if we introduce `skip-cabal-update` now it would stick, because even if we fix the handling of the boolean flags, we would want to do it in a backwards compatible way.  In particular, if workflows only used `true` and `false` for the "boolean" flags, they would work the same after the fix.  Only workflows that e.g. used `disable-matcher: foo` to disable the matcher would be broken by the fix.

I see three ways to go on from here:
1. Merge and release this PR and live with a slightly confusing separation of `"boolean"` and `boolean` flags.  Fix the flag syntax soonish.
2. Release with "boolean" `skip-cabal-update` flag.  No urgency to fix the flag syntax.
3. Fix the flag syntax first and postpone this PR until after that.

Depending on developer availability, 3 and the second part of 1 could take some time.  Alt 2 and the first part of 1 could move quickly since it is little work.

Comment (jneira) [reply setup/src/opts.ts:121]: good summary of alternatives, I am slightly in favour of the conservative one, and if the pr is meged in its actual state I would add a big warning in the readme and in the code itself noting the opposite semantics of the new option, comparing it with old ones explicitly

Comment (andreasabel) [reply setup/src/opts.ts:121]: @newhoggy : Since you originally opened issue #29, do you have a preference when it comes to `cabal-update: false` or `skip-cabal-update: true`?

Comment (newhoggy) [reply setup/src/opts.ts:121]: I don't have a preference.  Either is fine.

Comment (jneira) [reply setup/src/opts.ts:121]: to be clear: i also deeply *hate* negative flags and it is a good argument to do it right in the first place but with big warnings everywhere please

**Comment by andreasabel** [comment]
Planning to release this as 2.3.0.  Minor version bump because of new feature.

**Comment by andreasabel** [comment]
#### Final description of this PR:

This commit introduces a new boolean input `cabal-update` that defaults to `true`.  
If set to `false`, the `cabal update` step will be skipped.

The new flag `cabal-update` is proper boolean, it only accepts the YAML 1.2 truth values `true` and `false` (also in captial and uppercase).
This is contrast to other "boolean" flags that are "unset" by default and can be "set" with any non-empty string.

To test that `cabal update` happens, this commit also introduces a new Haskell test project into CI that depends on a common Hackage package (`base-orphans`).
